# Generated by Django 2.2.3 on 2019-07-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetData',
            new_name='student',
        ),
    ]
