# Generated by Django 2.2.3 on 2019-07-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190721_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='fName',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistSem', models.IntegerField()),
                ('secondSem', models.IntegerField()),
                ('thirdSem', models.IntegerField()),
                ('aggregate', models.IntegerField()),
                ('rollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='firstapp.Student')),
            ],
        ),
    ]
