# Generated by Django 2.2.3 on 2019-07-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20190721_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='rollNo',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='firstapp.Student'),
        ),
    ]
