# Generated by Django 2.2.3 on 2019-07-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20190721_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='firstapp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fName',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
